# Generated by Django 4.1 on 2022-10-04 07:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("Appointments", "0002_alter_appoinment_patient_phone_no"),
    ]

    operations = [
        migrations.CreateModel(
            name="AppoinmentPatient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("patient_name", models.CharField(max_length=100)),
                ("phone_no", models.CharField(max_length=10)),
                ("email", models.EmailField(max_length=254)),
                ("address", models.CharField(max_length=200)),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                (
                    "doctor_name",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="Doctor",
                        to="Appointments.doctor",
                        unique=True,
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="Appoinment_Patient",
        ),
    ]
